# ServiceAccount pour le frontend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: default
---
# ServiceAccount pour le backend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: default
---
# ServiceAccount pour la database
apiVersion: v1
kind: ServiceAccount
metadata:
  name: database-sa
  namespace: default
