{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-pg-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app.fullname" . }}-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "todo-app.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image | quote }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.db.user | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db.name | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-app.fullname" . }}-pg-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: {{ include "todo-app.fullname" . }}-pgdata
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "todo-app.fullname" . }}-postgres
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-deny-all
spec:
  podSelector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-postgres
  policyTypes:
  - Ingress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres-allow-from-backend
spec:
  podSelector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "todo-app.fullname" . }}-backend
    ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
{{- end }}